### PR TITLE
Update Russian translations for CJB Cheats Menu

### PR DESCRIPTION
**Pull request by D0n-A**
Added and fixed some points of the Russian translation.

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks again!

The `develop` branch has a new translation; feel free to just comment here with the text (or send another PR) if you want to translate it too.
> "player.instant-cooldowns": "Instant Cooldowns",

**Comment by D0n-A** [comment]
I apologize for the ridiculous question, but what are the "cooldowns" in this line related to? (for more correct translation). (Between weapon attacks? Or casting fishing rods , etc.?)

**Comment by Pathoschild** [comment]
@D0n-A It's the delay between special weapon/tool effects, when this colored background is shown:
>

**Comment by D0n-A** [comment]
@Pathoschild
When:
"player.instant-cooldowns": "Убрать задержку при использовании оружия / инструмента",

**Comment by D0n-A** [comment]
@Pathoschild
and fix
"controls.grow-crops": "Вырастить посевные культуры",

**Comment by Pathoschild** [comment]
Done, thanks again!

**Pull request merged**
