### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by Redlnn**

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! Can you provide a translation for this one too?
```js
    "tabs.advanced": "Advanced", // TODO
```

**Comment by Redlnn** [comment]
Sorry, I just didn't see it, I am preparing to submit a new commit

**Comment by Redlnn** [comment]
Ok, I have submitted a new commit.

**Comment by Pathoschild** [comment]
Thanks! Merged into `develop` for the upcoming CJB Cheats Menu 1.21.

**Pull request merged**
