### PR TITLE
Update Russian translations for CJB Cheats Menu

### PR DESCRIPTION
**Pull request by D0n-A**
Update Russian translations for CJB Cheats Menu (Beta)

### CODE REVIEW

**Comment by D0n-A** [comment]
Hello. Sorry for the offtop, but can I somehow connect localization and compatibility to the warps.json file for compatibility with the popular SVE mod? (BlueMoonVineyard, ShearwaterBridge, etc.).

**Comment by Pathoschild** [comment]
Thanks! Merged into `develop` for the upcoming CJB Cheats Menu 1.24.

**Comment by Pathoschild** [comment]
Currently you can't translate custom warps added by SVE, but I'll look into that to see how we could support that.

**Comment by D0n-A** [comment]
OK, wait)

**Pull request merged**
